// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9hILKeldSLH219sSh4MtzFknO1ZqFZY4',
    appId: '1:749062265693:web:53264e7a3075b75158e6b4',
    messagingSenderId: '749062265693',
    projectId: 'myfirebase-f2412',
    authDomain: 'myfirebase-f2412.firebaseapp.com',
    storageBucket: 'myfirebase-f2412.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDQTKtb3GCMDN2tIfSUCovJnEITdc6vpg',
    appId: '1:749062265693:android:14fb043848bb246458e6b4',
    messagingSenderId: '749062265693',
    projectId: 'myfirebase-f2412',
    storageBucket: 'myfirebase-f2412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGASql9NO1goE_QHI4s-IZwdhdp21UdI',
    appId: '1:749062265693:ios:a2d508cc06f9bc0f58e6b4',
    messagingSenderId: '749062265693',
    projectId: 'myfirebase-f2412',
    storageBucket: 'myfirebase-f2412.appspot.com',
    iosBundleId: 'com.example.posthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGASql9NO1goE_QHI4s-IZwdhdp21UdI',
    appId: '1:749062265693:ios:7f5a6aa5c9372e2158e6b4',
    messagingSenderId: '749062265693',
    projectId: 'myfirebase-f2412',
    storageBucket: 'myfirebase-f2412.appspot.com',
    iosBundleId: 'com.example.posthub.RunnerTests',
  );
}
